name: Windows Graphics Programmer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          target: 'desktop'
          arch: 'win64_mingw81'
          use-official: true
          email: ${{ secrets.QT_EMAIL }}
          pw: ${{ secrets.QT_PW }}
          cache: true
          tools: 'tools_qtcreator,qt.tools.qtcreator'

      - name: Build (Prepare QMake)
        run: cd ${{ github.workspace }}/windows_src_gui && mkdir ${{ github.workspace }}/windows_src_gui/build && qmake ${{ github.workspace }}/windows_src_gui/peggle_roguelike.pro -spec win32-g++ "CONFIG+=qtquickcompiler" && mingw32-make.exe qmake_all

      - name: Build
        run: jom

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_gui_build
          path: Peggle_Roguelike.exe
