name: Windows Graphics Programmer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          target: 'desktop'
          target_arch: 'win64_mingw81'
          use-official: true
          email: ${{ secrets.QT_EMAIL }}
          password: ${{ secrets.QT_PW }}
          cache: true
          tools: 'tools_qtcreator,qt.tools.qtcreator'

      - name: Prepare for build
        run: mkdir windows_src_gui/build && cd windows_src_gui/build
        
      - name: Build
        run: qmake ../Peggle_Roguelike.pro

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_build
          path: inventory_cli.exe
